### ISSUE TITLE
chromium-vaapi-65.0.3325.181-1 can't launch anymore after icu package update

### ISSUE THREAD

**Issue by julianxhokaxhiu** [maximbaz/chromium-vaapi-bin#2]
As the icu package got update today, Chromium is now searching for the *libicui18n.so.60* while now we have the *.61*.

Can you please provide a new build?

Thank you in advance.

**Comment by maximbaz** [comment]
Thanks for the ping, I was already made aware of this, it's compiling right now 🙂 

When the compilation of `-3` was almost done, a new patch was released for `-4` and I had to restart the build all over...

Should be ready in a few hours.

**Comment by maximbaz** [comment]
`-4` is taking longer than expected, I have to leave now and I won't be able to see it finish today. So I uploaded `-3` for now, and will upload `-4` tomorrow.
